title: jurlog
email: jurvidmar@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Jure Vidmar's personal blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jurlog.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jurc192

navbar_pages:
  - projects.html
  - blog.html
  - about.html

permalink: /:categories/:year-:month-:day-:title/

defaults:
  - scope: 
      path: "_posts"
    values:
      category: "blog"